version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - './data/mariadb_data:/bitnami/mariadb'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
  mediawiki:
    image: 'bitnami/mediawiki:latest'
    depends_on:
      - mariadb
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - './data/mediawiki-persistence:/bitnami/mediawiki'
      - './data/apache-persistence:/bitnami/apache'
